#define MONERO_VERSION_TAG "@VERSIONTAG@"
#define MONERO_VERSION "4.0.0"
#define MONERO_RELEASE_NAME "Something Good"
#define MONERO_VERSION_FULL MONERO_VERSION "-" MONERO_VERSION_TAG
#define MONERO_VERSION_IS_RELEASE @VERSION_IS_RELEASE@