name: Docker Image CI

on:
  push:
    branches: [ 3-update ]
  pull_request:
    branches: [ 3-update ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --target final-linux --file Dockerfile .
