name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - release-static-linux-x86_64
          - release-static-linux-armv6
          - release-static-linux-armv7
          - release-static-linux-armv8
          - release-static-linux-x86_64
          - release-static-freebsd-x86_64
          - release-static-mac-x86_64
          - release-static-linux-i686
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - run: docker build --build-arg RELEASE_TYPE=${{ matrix.target }} -t lthn/chain:${{ matrix.target }} .
