name: Docker Image CI

on:
  push:
    branches: [ 3-update ]
  pull_request:
    branches: [ 3-update ]

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build --target=base --file Dockerfile --build-arg BUILDKIT_INLINE_CACHE=1  .
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
  dep-linux:
    runs-on: ubuntu-latest
    needs: base
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build --target=depends-linux --file Dockerfile --build-arg BUILDKIT_INLINE_CACHE=1  .
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
  dep-win:
    runs-on: ubuntu-latest
    needs: base
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build --target=depends-windows --file Dockerfile --build-arg BUILDKIT_INLINE_CACHE=1  .
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
  dep-macos:
    runs-on: ubuntu-latest
    needs: base
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build --target=depends-linux --file Dockerfile --build-arg BUILDKIT_INLINE_CACHE=1  .
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
