name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-linux-gnu
          - x86_64-w64-mingw32
          - release-static-mac-x86_64
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - run: docker build --target ${{ matrix.target }} -t lthn/chain:${{ matrix.target }} .